language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn add coveralls
  - yarn test --coverage

after_script:
- COVERALLS_REPO_TOKEN=$repo_token
- yarn coveralls

